// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXOFZ7cMGh_oKr3XBMcn7HMrCxICBZbI',
    appId: '1:408707912486:web:da343df99b6eb7b39067e7',
    messagingSenderId: '408707912486',
    projectId: 'mixyspring2024',
    authDomain: 'mixyspring2024.firebaseapp.com',
    storageBucket: 'mixyspring2024.appspot.com',
    measurementId: 'G-G7537JQXEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfz2iNbuIoZLFQ9Rz5hC4O1iI3vz4olE4',
    appId: '1:408707912486:android:d7619fbb831ee0d39067e7',
    messagingSenderId: '408707912486',
    projectId: 'mixyspring2024',
    storageBucket: 'mixyspring2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtSbl9Oa85mz5zxtP4Jg3xQnAH2IYGcjg',
    appId: '1:408707912486:ios:2bac6fb142ac715e9067e7',
    messagingSenderId: '408707912486',
    projectId: 'mixyspring2024',
    storageBucket: 'mixyspring2024.appspot.com',
    iosBundleId: 'com.example.mixyDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtSbl9Oa85mz5zxtP4Jg3xQnAH2IYGcjg',
    appId: '1:408707912486:ios:d7edcf75d122a1ce9067e7',
    messagingSenderId: '408707912486',
    projectId: 'mixyspring2024',
    storageBucket: 'mixyspring2024.appspot.com',
    iosBundleId: 'com.example.mixyDemo.RunnerTests',
  );
}
