// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqLFkfqXO1dGh_G0GahGt8pVTl9AhrZEI',
    appId: '1:496142997358:web:d79ca6fadf09b938bc537f',
    messagingSenderId: '496142997358',
    projectId: 'mixy2024-5dcf8',
    authDomain: 'mixy2024-5dcf8.firebaseapp.com',
    storageBucket: 'mixy2024-5dcf8.appspot.com',
    measurementId: 'G-00SBF7CKRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrTNxodR3ENOyiUzHIxGBxVMoM5mOFkBs',
    appId: '1:496142997358:android:fdaa0cff520c127abc537f',
    messagingSenderId: '496142997358',
    projectId: 'mixy2024-5dcf8',
    storageBucket: 'mixy2024-5dcf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdjduG_MTjps6IY6BKu8xu4dbQ0WXS6Pk',
    appId: '1:496142997358:ios:7f16602959434347bc537f',
    messagingSenderId: '496142997358',
    projectId: 'mixy2024-5dcf8',
    storageBucket: 'mixy2024-5dcf8.appspot.com',
    iosClientId: '496142997358-sqiv0unh31rj09plduhn00ivaqm91t2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mixyDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdjduG_MTjps6IY6BKu8xu4dbQ0WXS6Pk',
    appId: '1:496142997358:ios:72a4f445783e7996bc537f',
    messagingSenderId: '496142997358',
    projectId: 'mixy2024-5dcf8',
    storageBucket: 'mixy2024-5dcf8.appspot.com',
    iosClientId: '496142997358-6m71vi8kfspov65bk782qab01giklq3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mixyDemo.RunnerTests',
  );
}
