name: main

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on windows virtual machine
    runs-on: windows-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '3.16.9' 
    
    # Get flutter dependencies.
    - run: flutter clean
    - run: flutter pub get
    
    # Build apk.
    - run: flutter build apk --release
    - run: flutter build apk --split-per-abi

    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - uses: actions/upload-artifact@v1
      with:
        name: armeabi-release-apk
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

        
#  code-coverage:
#    name: Check Code Coverage
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3

#      - name: Install Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'

#      - name: Install Dependencies
#        run: flutter pub get

#      - name: Run Flutter Tests
#        run: flutter test --coverage

#      - name: Setup LCOV
#        uses: hrishikesh-kadam/setup-lcov@v1

#      - name: Report Code Coverage
#        uses: zgosalvez/github-actions-report-lcov@v3
#        with:
#          coverage-files: coverage/lcov.info
#          minimum-coverage: 80
#          artifact-name: code-coverage-report
#          github-token: ${{ secrets.GITHUB_TOKEN }}
